/*
 * proto.h — THE wire contract for the Narbis Edge Earclip.
 *
 * Every BLE byte the device emits or accepts is defined here and only
 * here. tools/narbis_client/proto.py and tools/testapp/proto.js mirror
 * these layouts (constants cross-generated by tools/goldens/gen_proto_consts.py);
 * test_host/tests/t_proto_roundtrip.c and tools/tests/test_proto_roundtrip.py
 * prove C<->Python agreement with shared binary fixtures.
 *
 * Rules:
 *  - little-endian everywhere;
 *  - packed structs with _Static_assert(sizeof) locks;
 *  - STATUS is append-only (clients accept any length >= known fields);
 *  - EVENT records are {type,len,payload} — unknown types are skippable;
 *  - bump PROTO_VER minor for additive changes, major for breaking ones.
 */
#pragma once
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include "narbis/nc_types.h"

#define NC_PROTO_VER_MAJOR  1
#define NC_PROTO_VER_MINOR  1   /* 1.1: +TEST_LED_SWEEP_CONT (additive) */
#define NC_PROTO_VER        ((NC_PROTO_VER_MAJOR << 8) | NC_PROTO_VER_MINOR)

/* ------------------------------------------------------------------ */
/* GATT UUID allocation                                                */
/* 128-bit base: A5E9xxxx-C6A0-43C0-B0D0-6E6172626973 ("narbis")       */
/* xxxx = the 16-bit alias below at byte offset 2..3 (big-endian text) */
/* ------------------------------------------------------------------ */
#define NC_UUID_BASE_BYTES /* little-endian byte order for NimBLE */ \
    { 0x73, 0x69, 0x62, 0x72, 0x61, 0x6E, 0xD0, 0xB0,                \
      0xC0, 0x43, 0xA0, 0xC6, 0x00, 0x00, 0xE9, 0xA5 }
/* alias goes into bytes [12..13] of the array above (LE) */

#define NC_ALIAS_SENSOR_SVC   0x0100
#define NC_ALIAS_PPG          0x0101
#define NC_ALIAS_ACCEL        0x0102
#define NC_ALIAS_IBI          0x0103
#define NC_ALIAS_EVENT        0x0104
#define NC_ALIAS_STATUS       0x0105
#define NC_ALIAS_CONTROL      0x0106
#define NC_ALIAS_PROTO_VER    0x0107
#define NC_ALIAS_OTA_SVC      0x0200
#define NC_ALIAS_OTA_CTRL     0x0201
#define NC_ALIAS_OTA_DATA     0x0202

/* ATT payload budget at MTU 247 */
#define NC_ATT_PAYLOAD_MAX    244

#if defined(_MSC_VER)
#define NC_PACKED
#pragma pack(push, 1)
#else
#define NC_PACKED __attribute__((packed))
#endif

/* ------------------------------------------------------------------ */
/* PPG_STREAM  [hdr 15B][n x {i32 ir, i32 red (, i32 amb)}]            */
/* ------------------------------------------------------------------ */
typedef struct NC_PACKED {
    uint32_t seq;        /* per-stream, 0 at acquisition start */
    uint64_t t0_us;      /* device time of first sample        */
    uint8_t  rate_code;  /* nc_rate_t                          */
    uint8_t  n;
    uint8_t  flags;      /* NC_PPGF_* (nc_types.h)             */
} nc_ppg_hdr_t;

#define NC_PPG_HDR_SIZE        15
#define NC_PPG_MAX_N_NOAMB     28  /* 15 + 28*8  = 239 <= 244 */
#define NC_PPG_MAX_N_AMB       19  /* 15 + 19*12 = 243 <= 244 */

/* ------------------------------------------------------------------ */
/* ACCEL_STREAM [hdr 15B][n x {i16 x, i16 y, i16 z}]                   */
/* ------------------------------------------------------------------ */
typedef struct NC_PACKED {
    uint32_t seq;
    uint64_t t0_us;
    uint8_t  odr_code;   /* nc_acc_odr_t */
    uint8_t  n;
    uint8_t  flags;      /* NC_ACCF_* */
} nc_accel_hdr_t;

#define NC_ACCEL_HDR_SIZE      15
#define NC_ACCEL_MAX_N         38  /* 15 + 38*6 = 243 <= 244 */

#define NC_ACCF_FS_MASK        0x03 /* 0=±2g 1=±4g 2=±8g 3=±16g */
#define NC_ACCF_FIFO_OVERRUN   (1u << 2)

/* ------------------------------------------------------------------ */
/* IBI_STREAM [u32 seq][u8 n][n x 12B]                                 */
/* ------------------------------------------------------------------ */
typedef struct NC_PACKED {
    uint64_t t_beat_us;
    uint16_t ibi_ms;
    uint8_t  confidence;  /* 0..100 */
    uint8_t  flags;       /* NC_IBIF_* (nc_types.h) */
} nc_ibi_rec_t;

#define NC_IBI_HDR_SIZE        5
#define NC_IBI_REC_SIZE        12
#define NC_IBI_MAX_N           19  /* 5 + 19*12 = 233 <= 244 */

/* ------------------------------------------------------------------ */
/* EVENT_STREAM [u32 seq][u8 n][n x {u8 type, u8 len, payload}]        */
/* Wire payload always starts with u64 t_us, then the type's fields    */
/* (== nc_event_t.data). len = 8 + internal len. Unknown types are     */
/* skippable via len.                                                  */
/* ------------------------------------------------------------------ */
#define NC_EVENT_HDR_SIZE      5
#define NC_EVENT_REC_MAX       (2 + 8 + 14)  /* type+len+t_us+data */

/* wire payload lengths (t_us included) */
#define NC_EVLEN_AGC_STEP      13  /* t_us, led, old_ma, new_ma, old_rf, new_rf */
#define NC_EVLEN_GATE          10  /* t_us, state, reason_mask                  */
#define NC_EVLEN_WEAR          9   /* t_us, worn                                */
#define NC_EVLEN_MARKER        11  /* t_us, source, u16 marker_id               */
#define NC_EVLEN_ERROR         14  /* t_us, u16 code, u32 arg                   */
#define NC_EVLEN_RATE_CHANGE   10  /* t_us, old_code, new_code                  */
#define NC_EVLEN_AGC_OFFDAC    11  /* t_us, phase, old_code, new_code           */
#define NC_EVLEN_SELFTEST_DONE 10  /* t_us, pass_count, fail_count              */

#define NC_MARKER_SRC_BUTTON   0
#define NC_MARKER_SRC_HOST     1

/* NC_EV_ERROR codes */
typedef enum {
    NC_ERR_NONE = 0,
    NC_ERR_I2C = 1,            /* arg = consecutive failure count      */
    NC_ERR_AFE_INIT = 2,
    NC_ERR_ACCEL_INIT = 3,
    NC_ERR_PPG_OVERRUN = 4,    /* afe_rdy_q or ppg_queue overflow      */
    NC_ERR_FIFO_OVERRUN = 5,   /* LIS2DH12 FIFO                        */
    NC_ERR_NOTIFY_DROP = 6,    /* arg = cumulative drops               */
    NC_ERR_NVS = 7,
    NC_ERR_OTA = 8,
    NC_ERR_BROWNOUT = 9
} nc_error_code_t;

/* ------------------------------------------------------------------ */
/* STATUS — 32 bytes, append-only                                      */
/* ------------------------------------------------------------------ */
typedef struct NC_PACKED {
    uint8_t  sys_state;            /* nc_sys_state_t */
    uint8_t  flags;                /* NC_STF_* */
    uint16_t batt_mv;
    uint8_t  batt_pct;
    uint8_t  ppg_rate_code;
    uint8_t  led_ir_ma;
    uint8_t  led_red_ma;
    uint8_t  tia_gain_code;        /* RF code 0..7 */
    uint8_t  tia_cf_code;          /* CF code 0..7 */
    uint16_t gate_duty_x100;       /* 0..10000 over 60 s window */
    uint32_t notif_drop_count;
    uint16_t i2c_err_count;
    int16_t  clock_drift_ppm_x10;  /* 0x7FFF = unknown */
    uint32_t uptime_s;
    uint16_t ibi_last_ms;
    uint8_t  hr_bpm;               /* smoothed; 0 = none */
    uint8_t  btn_pressed;          /* live GPIO2 level (1 = held), proto 1.1 */
    uint8_t  reserved[4];
} nc_status_t;

#define NC_STF_CHARGING       (1u << 0)
#define NC_STF_CHARGE_DONE    (1u << 1)
#define NC_STF_USB            (1u << 2)
#define NC_STF_WORN           (1u << 3)
#define NC_STF_GATE           (1u << 4)
#define NC_STF_AGC_FROZEN     (1u << 5)
#define NC_STF_HRS_ACTIVE     (1u << 6)
#define NC_STF_LOWBATT_WARN   (1u << 7)

/* ------------------------------------------------------------------ */
/* CONTROL: request [u8 op][u8 tid][payload]                           */
/*          response indication [u8 op|0x80][u8 tid][u8 status][pl]    */
/* One outstanding request at a time (else NC_ST_BUSY).                */
/* ------------------------------------------------------------------ */
typedef enum {
    NC_OP_STREAM_START     = 0x01, /* u8 mask: b0 PPG b1 ACCEL b2 IBI b3 EVENT */
    NC_OP_STREAM_STOP      = 0x02, /* u8 mask */
    NC_OP_SET_RATE         = 0x03, /* u8 rate_code */
    NC_OP_KNOB_GET         = 0x10, /* u16 id -> {u16 id, i32 value} */
    NC_OP_KNOB_SET         = 0x11, /* {u16 id, i32 value} */
    NC_OP_KNOB_SAVE        = 0x12,
    NC_OP_KNOB_RESET       = 0x13, /* u8 scope: 0 RAM, 1 RAM+NVS */
    NC_OP_KNOB_DISCOVER    = 0x14, /* u16 start_index -> chunk (below) */
    NC_OP_TIME_SYNC        = 0x20, /* u64 host_epoch_us -> {u64 echo, u64 dev_t_us} */
    NC_OP_GET_TIME         = 0x21, /* -> u64 dev_t_us */
    NC_OP_MARKER           = 0x30, /* u16 marker_id (0 = unnumbered) */
    NC_OP_AGC_FREEZE       = 0x40, /* u8 freeze */
    NC_OP_AGC_MANUAL       = 0x41, /* {u8 ir_ma,u8 red_ma,u8 rf_code,u8 apply_mask:
                                       b0 ir, b1 red, b2 gain} */
    NC_OP_SELFTEST_RUN     = 0x50, /* u32 test_mask (0 = all) */
    NC_OP_SELFTEST_RESULT  = 0x51, /* u16 offset -> {u16 total,u16 off,u8 n,bytes} */
    NC_OP_ENTER_OTA        = 0x60,
    NC_OP_POWER_OFF        = 0x70,
    NC_OP_REBOOT           = 0x71,
    NC_OP_FACTORY_RESET    = 0x72, /* u32 magic NC_FACTORY_MAGIC */

    /* TEST block — only when built with NARBIS_TEST_MODE=1 */
    NC_OP_TEST_SELFTEST_ONE = 0xE0, /* u8 test_id */
    NC_OP_TEST_LED_DRIVE    = 0xE1, /* {u8 led(0 IR,1 RED), u8 ma, u16 duration_ms} */
    NC_OP_TEST_LED_SWEEP    = 0xE2, /* {u8 led, u8 ma_step} -> result via SELFTEST_RESULT-style chunks */
    NC_OP_TEST_RX_SWEEP     = 0xE3, /* {u8 what: 0 TIA gain, 1 offset DAC} */
    NC_OP_TEST_RATE_COUNT   = 0xE4, /* u8 seconds -> {u32 pulses, u32 elapsed_ms} (async done event) */
    NC_OP_TEST_BUTTON_ECHO  = 0xE5, /* u8 enable — edges stream as MARKER events src=button */
    NC_OP_TEST_CHARGER_LIVE = 0xE6, /* u8 enable — VUSB/STAT snapshot @2 Hz on EVENT_STREAM */
    NC_OP_TEST_BATT_RAW     = 0xE7, /* -> {u16 mv_cal, u16 adc_raw_avg} */
    NC_OP_TEST_ACCEL_LIVE   = 0xE8, /* u8 enable max-ODR live + overrun counter */
    NC_OP_TEST_SLEEP_NOW    = 0xE9, /* enter OFF in 10 s (current measurement) */
    NC_OP_TEST_REPORT       = 0xEA, /* u16 offset -> consolidated report blob chunk */
    NC_OP_TEST_LED_SWEEP_CONT = 0xEB /* {u8 mask: b0 IR, b1 RED; u8 enable;
                                        u8 phase_s (0 -> 5)} — continuous
                                        0->max->0 triangle with holds:
                                        ramp up phase_s, hold max phase_s,
                                        ramp down phase_s, hold 0 phase_s,
                                        repeat until enable=0/disconnect.
                                        Freezes AGC on start. */
} nc_opcode_t;

/* Responses set bit7 (op | NC_OP_RESP_FLAG). TEST-block opcodes (0xE0+)
 * already carry bit7: their responses echo the opcode UNCHANGED — clients
 * correlate TEST responses by tid alone. */
#define NC_OP_RESP_FLAG        0x80
#define NC_FACTORY_MAGIC       0x4E415242u /* "NARB" */

#define NC_STREAM_MASK_PPG     (1u << 0)
#define NC_STREAM_MASK_ACCEL   (1u << 1)
#define NC_STREAM_MASK_IBI     (1u << 2)
#define NC_STREAM_MASK_EVENT   (1u << 3)

typedef enum {
    NC_ST_OK = 0,
    NC_ST_UNKNOWN_OP = 1,
    NC_ST_BAD_LEN = 2,
    NC_ST_BAD_PARAM = 3,
    NC_ST_OUT_OF_RANGE = 4,
    NC_ST_READ_ONLY = 5,
    NC_ST_BUSY = 6,
    NC_ST_WRONG_STATE = 7,
    NC_ST_NVS_ERR = 8,
    NC_ST_CRC_ERR = 9,
    NC_ST_VERSION_MISMATCH = 10,
    NC_ST_NEEDS_RESTART = 11,  /* success, effect deferred to restart */
    NC_ST_UNAUTHORIZED = 12,
    NC_ST_LOWBATT = 13
} nc_ctrl_status_t;

/* Knob discovery chunk: [u16 total][u16 first_idx][u8 n][n x record]
 * record = {u16 id, u8 type, u8 flags, i32 min, i32 max, i32 def,
 *           i32 current, u8 name_len, name..., u8 unit_len, unit...}   */
#define NC_KNOB_DISC_HDR_SIZE  5
#define NC_KNOB_REC_FIXED      21  /* id(2)+type+flags+min/max/def/current(16)+name_len(1);
                                      strings + unit_len byte follow */

typedef enum {
    NC_KNOB_BOOL = 0,
    NC_KNOB_U8 = 1,
    NC_KNOB_U16 = 2,
    NC_KNOB_I32 = 3
} nc_knob_type_t;

#define NC_KF_PERSIST   (1u << 0)
#define NC_KF_LIVE      (1u << 1)  /* applies immediately              */
#define NC_KF_RESTREAM  (1u << 2)  /* applies at next stream start     */
#define NC_KF_REBOOT    (1u << 3)  /* needs restart                    */

/* ------------------------------------------------------------------ */
/* OTA service                                                         */
/* OTA_DATA (write-no-response): [u32 offset][data <= 240B]            */
/* OTA_CTRL request/response use the CONTROL envelope ([op][tid]...)   */
/* ------------------------------------------------------------------ */
typedef enum {
    NC_OTA_BEGIN = 0x01,   /* {u32 size, u32 crc32, u8 vlen, char v[]}
                              -> {u32 resume_offset} */
    NC_OTA_STATUS = 0x02,  /* -> {u8 state, u32 bytes_rx, u16 last_err} */
    NC_OTA_FINISH = 0x03,  /* validate + set boot + restart */
    NC_OTA_ABORT = 0x04
} nc_ota_op_t;

#define NC_OTA_CHUNK_MAX      240

typedef enum {
    NC_OTA_IDLE = 0,
    NC_OTA_RECEIVING = 1,
    NC_OTA_VALIDATING = 2,
    NC_OTA_READY = 3,
    NC_OTA_FAILED = 4
} nc_ota_state_t;

typedef enum {
    NC_OTAERR_NONE = 0,
    NC_OTAERR_EXPECTED_OFFSET = 1, /* host must GET_STATUS + reseek */
    NC_OTAERR_SIZE = 2,
    NC_OTAERR_CRC = 3,
    NC_OTAERR_IMAGE = 4,
    NC_OTAERR_FLASH = 5,
    NC_OTAERR_STATE = 6
} nc_ota_err_t;

/* ------------------------------------------------------------------ */
/* Self-test result blob (CONTROL 0x51 chunks):                        */
/* [u8 blob_ver][u64 t_run_us][u8 n][n x {u8 id,u8 status,i32 val,i32 thr}] */
/* ------------------------------------------------------------------ */
#define NC_ST_BLOB_VER        1
#define NC_ST_REC_SIZE        10

typedef enum {
    NC_TEST_I2C_SCAN = 1,
    NC_TEST_ACCEL_WHOAMI = 2,
    NC_TEST_AFE_REG_RW = 3,
    NC_TEST_AFE_DARK = 4,
    NC_TEST_XTALK = 5,
    NC_TEST_ACCEL_ST = 6,
    NC_TEST_BATT = 7,
    NC_TEST_CHARGER = 8,
    NC_TEST_COUNT_ = 8
} nc_selftest_id_t;

typedef enum { NC_TR_PASS = 0, NC_TR_FAIL = 1, NC_TR_SKIP = 2 } nc_test_status_t;

#if defined(_MSC_VER)
#pragma pack(pop)
#endif

_Static_assert(sizeof(nc_ppg_hdr_t) == NC_PPG_HDR_SIZE, "ppg hdr packing");
_Static_assert(sizeof(nc_accel_hdr_t) == NC_ACCEL_HDR_SIZE, "accel hdr packing");
_Static_assert(sizeof(nc_ibi_rec_t) == NC_IBI_REC_SIZE, "ibi rec packing");
_Static_assert(sizeof(nc_status_t) == 32, "status packing");
