/*
 * dsp_coeffs_gen.h -- GENERATED by tools/goldens/gen_dsp_coeffs.py.
 * DO NOT EDIT; rerun the generator (then gen_dsp_vectors.py) instead.
 *
 * Include only from nc_dsp.c, after narbis/nc_dsp.h (needs
 * nc_bq_coeff_t and NC_RATE_COUNT).
 *
 * Derivation:
 *  - band-pass: scipy.signal.butter(2, [0.5, 8.0], 'bandpass',
 *    output='zpk') per rate -> zpk2sos with the overall gain k split
 *    sqrt(k) per section (all-in-one-section would put |b1| = 2.0
 *    outside Q30) -> 2 cascaded biquads, Q30, a0 dropped;
 *  - notch: scipy.signal.iirnotch(f0, Q=8) at 50/60 Hz where
 *    f0 <= 0.45*fs (zeroed + valid=0 otherwise);
 *  - DC alpha (default hp fc = 0.5 Hz):
 *    alpha_q31 = round(2^31 * (1 - exp(-2*pi*fc/fs)));
 *  - post-quantization pole radii asserted < 0.9995 by the
 *    generator. Table index == nc_rate_t.
 */
#pragma once

/* 4th-order Butterworth band-pass 0.5-8.0 Hz: [rate][section] */
static const nc_bq_coeff_t nc_dsp_bp_sos[NC_RATE_COUNT][2] = {
    { /* 50 sps */
        { .b0 = 388787132, .b1 = 777574264, .b2 = 388787132, .a1 = -797223837, .a2 = 319027773 },
        { .b0 = 388787132, .b1 = -777574264, .b2 = 388787132, .a1 = -2052976606, .a2 = 983746501 },
    },
    { /* 100 sps */
        { .b0 = 218087345, .b1 = 436174691, .b2 = 218087345, .a1 = -1466595336, .a2 = 576519952 },
        { .b0 = 218087345, .b1 = -436174691, .b2 = 218087345, .a1 = -2100439942, .a2 = 1027858232 },
    },
    { /* 200 sps */
        { .b0 = 116922955, .b1 = 233845909, .b2 = 116922955, .a1 = -1807955791, .a2 = 786457352 },
        { .b0 = 116922955, .b1 = -233845909, .b2 = 116922955, .a1 = -2124010670, .a2 = 1050562502 },
    },
    { /* 250 sps */
        { .b0 = 94953073, .b1 = 189906145, .b2 = 94953073, .a1 = -1876338559, .a2 = 836978390 },
        { .b0 = 94953073, .b1 = -189906145, .b2 = 94953073, .a1 = -2128712681, .a2 = 1055159241 },
    },
    { /* 500 sps */
        { .b0 = 48976837, .b1 = 97953675, .b2 = 48976837, .a1 = -2012626401, .a2 = 947992681 },
        { .b0 = 48976837, .b1 = -97953675, .b2 = 48976837, .a1 = -2138105337, .a2 = 1064410827 },
    },
};

/* 50 Hz notch, Q=8; all-zero rows are invalid rates */
static const nc_bq_coeff_t nc_dsp_notch50[NC_RATE_COUNT] = {
    { .b0 = 0, .b1 = 0, .b2 = 0, .a1 = 0, .a2 = 0 }, /* 50 sps */
    { .b0 = 0, .b1 = 0, .b2 = 0, .a1 = 0, .a2 = 0 }, /* 100 sps */
    { .b0 = 977469483, .b1 = 0, .b2 = 977469483, .a1 = 0, .a2 = 881197142 }, /* 200 sps */
    { .b0 = 995401989, .b1 = -615192261, .b2 = 995401989, .a1 = -615192261, .a2 = 917062153 }, /* 250 sps */
    { .b0 = 1033149278, .b1 = -1671670648, .b2 = 1033149278, .a1 = -1671670648, .a2 = 992556733 }, /* 500 sps */
};

/* 1 where 50 <= 0.45*fs (nc_dsp_init auto-disable rule) */
static const uint8_t nc_dsp_notch50_valid[NC_RATE_COUNT] = { 0, 0, 1, 1, 1 };

/* 60 Hz notch, Q=8; all-zero rows are invalid rates */
static const nc_bq_coeff_t nc_dsp_notch60[NC_RATE_COUNT] = {
    { .b0 = 0, .b1 = 0, .b2 = 0, .a1 = 0, .a2 = 0 }, /* 50 sps */
    { .b0 = 0, .b1 = 0, .b2 = 0, .a1 = 0, .a2 = 0 }, /* 100 sps */
    { .b0 = 960105813, .b1 = 593378025, .b2 = 960105813, .a1 = 593378025, .a2 = 846469801 }, /* 200 sps */
    { .b0 = 981009156, .b1 = -123196149, .b2 = 981009156, .a1 = -123196149, .a2 = 888276488 }, /* 250 sps */
    { .b0 = 1025385855, .b1 = -1494948238, .b2 = 1025385855, .a1 = -1494948238, .a2 = 977029885 }, /* 500 sps */
};

/* 1 where 60 <= 0.45*fs (nc_dsp_init auto-disable rule) */
static const uint8_t nc_dsp_notch60_valid[NC_RATE_COUNT] = { 0, 0, 1, 1, 1 };

/* DC tracker alpha, Q31, default fc = 0.5 Hz */
static const int32_t nc_dsp_dc_alpha_q31[NC_RATE_COUNT] = { 130778818, 66416459, 33469041, 26817225, 13450737 };
